async () => {
const q=__BB;q.stop();q.start();q.step(2);let trace=[],tests=[],frames=0,inputs=new Set(),lastSwing=-1000,lastThrow=-1000;
function check(name,pass,detail){tests.push({name,passed:!!pass,detail});}
function pose(){return{x:+q.player.x.toFixed(2),y:+q.player.y.toFixed(2),z:+q.player.z.toFixed(2),hp:q.player.hp,ground:q.player.floorId};}
function key(code,down){if(down&&!inputs.has(code)){q.press(code);inputs.add(code);}if(!down&&inputs.has(code)){q.release(code);inputs.delete(code);}}
function clear(){q.clear();inputs.clear();}
function tick(n=1,combat=false){for(let i=0;i<n;i++){if(combat){let e=q.world.enemies.filter(e=>!e.dead&&Math.abs(e.y-q.player.y)<1.5).sort((a,b)=>Math.hypot(a.x-q.player.x,a.z-q.player.z)-Math.hypot(b.x-q.player.x,b.z-q.player.z))[0];if(e){let d=Math.hypot(e.x-q.player.x,e.z-q.player.z);if(d<2.4&&frames-lastSwing>18){q.press('KeyJ');lastSwing=frames;}if(frames-lastSwing===1)q.release('KeyJ');if(e.type==='beetle'&&d<5&&e.stun<.5&&frames-lastThrow>105){q.press('KeyQ');lastThrow=frames;}if(frames-lastThrow===1)q.release('KeyQ');}}q.step(1);frames++;}}
function drive(x,z){let dx=x-q.player.x,dz=z-q.player.z;key('KeyD',dx>.13);key('KeyA',dx<-.13);key('KeyS',dz>.13);key('KeyW',dz<-.13);}
function walk(x,z,label,max=900){clear();let i=0,startFalls=q.data.stats.falls;while(Math.hypot(q.player.x-x,q.player.z-z)>.25&&q.state==='playing'&&i++<max){drive(x,z);tick(1,true);if(q.data.stats.falls>startFalls)break;}clear();tick(10);let ok=Math.hypot(q.player.x-x,q.player.z-z)<.6;trace.push({label,ok,pose:pose()});if(!ok)throw Error('Cannot walk '+label+' '+JSON.stringify(pose()));}
function jump(x,z,label,double=false,sprint=true,max=220){clear();let startFalls=q.data.stats.falls,landed=false;key('ShiftLeft',sprint);drive(x,z);key('Space',true);let i=0;for(;i<max;i++){drive(x,z);if(double&&i===21)key('Space',false);if(double&&i===23)key('Space',true);if(i===50)key('Space',false);tick(1,true);if(q.data.stats.falls>startFalls)break;if(i>8&&q.player.grounded&&Math.hypot(q.player.x-x,q.player.z-z)<.8){landed=true;break;}}
clear();tick(8);let ok=landed&&q.data.stats.falls===startFalls;trace.push({label,ok,pose:pose(),frames:i});if(!ok)throw Error('Cannot jump '+label+' '+JSON.stringify(pose()));}

function ride(id,side,label){clear();let m=q.world.moving.find(p=>p.id===id),wait=0;while((side<0?m.x>-2.8:m.x<2.8)&&wait++<800)tick(1,true);let startFalls=q.data.stats.falls;key('Space',true);key('ShiftLeft',true);let success=false;for(let i=0;i<160;i++){drive(m.x,m.z);tick(1,true);if(i>5&&q.player.grounded&&q.player.floorId===id){success=true;break;}if(q.data.stats.falls>startFalls)break;}clear();tick(3);check(label+' landing on moving platform',success,pose());if(!success)throw Error('Cannot board '+label+' '+JSON.stringify(pose()));wait=0;while((side<0?m.x<2:m.x>-2)&&wait++<1000)tick(1,true);trace.push({label:label+' ride',pose:pose()});}

function dialogs(){clear();for(let i=0;i<8&&q.state==='dialogue';i++)q.dialog();if(q.state==='reward')q.reward();}
async function portal(x,z,to){walk(x,z,'arch to '+to);q.interact();await new Promise(r=>setTimeout(r,450));check('Actual portal travel to '+to,q.room===to,{room:q.room});if(q.room!==to)throw Error('portal failed '+to);tick(5);clear();}
function ring(label,max=7){clear();for(let i=0;i<max;i++){key('KeyQ',true);tick(1);key('KeyQ',false);tick(140,true);}trace.push({label,pose:pose(),switches:q.world.switches.map(s=>[s.id,s.on])});}
try{
walk(0,5,'Moss');q.interact();dialogs();walk(5.8,2.2,'crate');key('KeyE',true);key('KeyW',true);tick(73);clear();tick(5);check('Workshop solved with actual controls',q.data.flags.workshop,pose());
walk(8,-4,'workshop doorway');walk(12.5,-4,'workshop chest');q.interact();dialogs();check('Sunring obtained through the real workshop',q.data.ring,pose());walk(8,-4,'leave workshop');walk(8,1.3,'go around workshop fence');walk(20,1.3,'past workshop');await portal(21,-1,'brook');
walk(-6,12.3,'left bank approach');jump(-8,8,'left stepping stone');jump(-13,8,'west bank');walk(-18,-8.5,'west rune');ring('west rune');check('Western river rune is lit on foot',q.data.flags['brook.reed']);
walk(-11.25,-5,'west bank crossing');jump(-6,-5,'jump west bank to mill');walk(5.7,-10,'mill east side');jump(9,-10,'east stone');jump(13,-10,'east bank');walk(18,-18.5,'east rune');ring('east rune');check('Eastern rune is lit on foot',q.data.flags['brook.river']);
walk(13,-23,'north from east bank');ring('north rune');check('Third rune is reachable before the bridge opens',q.data.flags['brook.sun']);walk(13,-10,'return down east bank');jump(9,-10,'east stone return');jump(4,-10,'mill return');walk(0,-14,'north bridge approach');jump(0,-19,'raised bridge');walk(0,-25,'bridge end');jump(0,-29,'northern shrine');walk(0,-31.3,'River Bell');q.interact();dialogs();check('River Bell reached with uninterrupted physical traversal',q.data.bells[0]&&q.data.airjump,pose());await portal(0,-36,'hearth');
walk(18,2,'east path home');walk(6,2,'village square east');walk(-6,0,'village square west');await portal(-21,-1,'sun');
walk(-4,12,'Sunstep approach');jump(-8,8,'first raised stair',true);jump(-12,3,'lower terrace',true);walk(-13,1,'first spindle');check('First wind spindle reached on foot',q.data.flags['sun.spindle-west']);walk(-5,-1,'eastward terrace edge');ride('crosswind',-1,'crosswind');jump(5,-3,'crosswind crossing',true);walk(13,-9,'second spindle');check('Second wind spindle reached on foot',q.data.flags['sun.spindle-east']);walk(4,-11.5,'upper crossing edge');ride('highwind',1,'highwind');jump(-5,-15.5,'highwind crossing',true);walk(-12,-18,'high lantern');walk(-10,-22,'third spindle');check('Third wind spindle reached on foot',q.data.flags['sun.spindle-high']);walk(-7,-23,'last stair approach');jump(-5,-27,'last stair',true);jump(0,-31,'summit',true);walk(1,-32.3,'Sky Bell');q.interact();dialogs();check('Sky Bell reached by actual air jumps',q.data.bells[1]&&q.data.empowered,pose());await portal(1,-38,'hearth');
walk(-18,1,'west path home');walk(-5,0,'middle square');walk(0,-19,'northern path');await portal(0,-23,'moon');walk(0,10,'bramble barrier');key('KeyJ',true);tick(44);key('KeyJ',false);tick(6);walk(-8,8,'sanctuary path');walk(-16,-7.8,'first prism');q.interact();tick(3);walk(-10,-10,'first beam path');walk(7.8,-10,'second prism');q.interact();tick(3);q.interact();tick(3);walk(10,-23,'north beam');walk(10,-25,'third prism');q.interact();tick(3);q.interact();tick(3);check('Prism chain solved through actual interactions',q.data.flags.moonSolved,pose());walk(-1,-26,'shrine approach');jump(-5,-26,'moon shrine jump',true);walk(-9,-25.3,'Moon Bell');q.interact();dialogs();check('Third Bell reached through the full route',q.data.bells.every(Boolean),pose());await portal(-9,-30,'hearth');
walk(0,-19,'home north');walk(9,-16,'great tree path');await portal(15,-21,'crown');walk(0,5,'warden threshold');
// React to visible attacks with ordinary keys. No player or enemy state manipulation.
let bossStartFalls=q.data.stats.falls,bossFrames=0,phaseSeen=new Set(),lastJump=-1000,prevMode='';clear();
while(!q.data.won&&bossFrames++<15000){const b=q.world.boss;if(!b)break;phaseSeen.add(b.phase);let p=q.player;let danger=q.world.rings.filter(r=>r.kind==='danger'&&r.life>0);let shocks=q.world.rings.filter(r=>r.kind==='shock');
if(b.mode==='stunned'){drive(0,-2.3);if(Math.hypot(p.x-b.x,p.z-b.z)<3.8&&frames-lastSwing>20){key('KeyJ',true);lastSwing=frames;}if(frames-lastSwing===1)key('KeyJ',false);}
else if(b.mode==='open'){drive(0,3.0);if(frames-lastThrow>110){key('KeyQ',true);lastThrow=frames;}if(frames-lastThrow===1)key('KeyQ',false);}
else{let tx=b.mode==='roots'?7:0,tz=4;drive(tx,tz);let incoming=shocks.some(r=>{let d=Math.hypot(p.x-r.x,p.z-r.z)-r.r;return d>0&&d<2.1;});if(incoming&&p.grounded&&frames-lastJump>25){key('Space',true);lastJump=frames;}if(frames-lastJump>32)key('Space',false);}
tick(1);if(q.state==='dialogue')break;
}
clear();check('Full guardian defeated using normal movement, jumping, ring and blade input',q.data.won,{frames:bossFrames,health:q.player.hp,faints:q.data.flags.faints||0,phases:[...phaseSeen]});dialogs();check('Complete uninterrupted adventure reaches its ending',q.state==='ending',{time:q.data.stats.time,falls:q.data.stats.falls});
}catch(e){check('Route completed',false,{error:e.message,pose:pose(),state:q.state,room:q.room,data:q.data});}
q.render();return{tests,trace,frames,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed),diagnostics:Bramblebound.diagnostics()};
}
