// Fixed-step gameplay. Positions refer to the soles of characters, not their centers.
function surfaces(){let out=grounds.concat(moving);for(let g of gates)if(g.bridge&&D.flags[g.flag])out.push({id:g.id,x:g.x,z:g.z,w:g.w,d:g.d,y:g.y,bottom:g.y-.3});return out;}
function insideSurface(p,x,z,margin=0){return Math.abs(x-p.x)<=p.w/2+margin&&Math.abs(z-p.z)<=p.d/2+margin;}
function floorAt(x,z,maxY=100){let found=null;for(let s of surfaces())if(s.y<=maxY+.001&&insideSurface(s,x,z)&&(!found||s.y>found.y))found=s;return found;}
function walls(ignore=''){let out=solids.slice();for(let g of gates)if(!g.bridge&&!D.flags[g.flag])out.push(g);for(let h of thorns)if(!h.broken)out.push(h);for(let c of crates)if(c.id!==ignore)out.push({x:c.x,z:c.z,w:c.w,d:c.d,y:c.y,h:1.3,id:c.id});for(let s of surfaces())out.push({x:s.x,z:s.z,w:s.w,d:s.d,y:s.bottom,h:s.y-s.bottom,terrain:true});return out;}
function resolveAxis(obj,axis,delta,r=.33,height=1.6,ignore=''){if(!delta)return;obj[axis]+=delta;for(let w of walls(ignore)){if(obj.y>=w.y+w.h-(w.terrain?.32:.04)||obj.y+height<=w.y+.04)continue;if(w.kind==='circle'){let dx=obj.x-w.x,dz=obj.z-w.z,rr=Math.max(w.w,w.d)/2+r,dist=Math.hypot(dx,dz);if(dist<rr){if(dist<.0001){obj[axis]+=Math.sign(delta)*rr;continue;}let k=(rr-dist)/dist;obj.x+=dx*k;obj.z+=dz*k;}continue;}
let hx=w.w/2+r,hz=w.d/2+r;if(Math.abs(obj.x-w.x)<hx-.0001&&Math.abs(obj.z-w.z)<hz-.0001){obj[axis]=(axis==='x'?w.x:w.z)+(delta>0?-1:1)*(axis==='x'?hx:hz);}}
}
function blockedPoint(x,y,z,r=.05){for(let w of walls()){if(y<w.y||y>w.y+w.h)continue;if(Math.abs(x-w.x)<w.w/2+r&&Math.abs(z-w.z)<w.d/2+r)return true;}return false;}
function canSee(a,b){let d=V.sub(b,a),n=Math.ceil(V.len(d)*3);for(let i=1;i<n;i++){let k=i/n;if(blockedPoint(a[0]+d[0]*k,a[1]+d[1]*k,a[2]+d[2]*k,0))return false;}return true;}
function burst(x,y,z,n=15,color=[1,.72,.29],speed=3){for(let i=0;i<n&&particles.length<600;i++){let a=Math.random()*TAU,v=speed*(.3+Math.random()*.7),life=.4+Math.random()*.45;particles.push({x,y,z,vx:Math.sin(a)*v,vy:1+Math.random()*v,vz:Math.cos(a)*v,life,max:life,size:.025+Math.random()*.025,c:color,gravity:5});}}
function showScreen(id){activeScreen=id;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('on',s.id===id));$('hud').classList.toggle('on',!['menu','confirm','about','loading'].includes(state)&&gameStarted);$('touch').classList.toggle('play',state==='playing');$('dialogue').style.display=state==='dialogue'?'block':'none';$('prompt').style.display='none';}
function showMenu(){state='menu';$('menu').classList.add('on');$('continueBtn').classList.toggle('hidden',!savedData);$('newBtn').classList.toggle('primary',!savedData);$('newBtn').classList.toggle('secondary',!!savedData);showScreen('menu');}
function toast(text,duration=3){toastText=text;$('toast').textContent=controlText(text);$('toast').classList.add('show');toastTimer=duration;}
function hint(text,duration=6){$('contextHint').textContent=controlText(text);$('contextHint').style.opacity='1';hintTimer=duration;}
function showArea(name){let r=ROOMS[name];$('areaKicker').textContent=r.tag;$('areaName').textContent=r.name;$('areaSub').textContent=r.sub;$('areaCard').style.opacity='1';areaTimer=4.5;$('placeLabel').textContent=r.name.toUpperCase();}
function startNew(force=false){AudioSys.start();if(savedData&&!force){state='confirm';showScreen('confirm');return;}D=newData();savedData=null;player.hp=player.maxHp=8;player.angle=Math.PI;player.combo=0;player.invuln=2;gameStarted=true;state='playing';clearInput();buildWorld('hearth',[0,0,16]);showScreen('');saveGame();hint('WASD to wander. Space to jump. Find Moss by the well and press E.',10);}
function continueGame(){AudioSys.start();if(!savedData){startNew(true);return;}try{D=validateSave(savedData);}catch{D=newData();}gameStarted=true;player.hp=player.maxHp=D.maxHp;state='playing';clearInput();const p=D.checkpoint;buildWorld(D.room,p?[p.x,p.y,p.z]:undefined);showScreen('');hint('Welcome back. Tab opens your map and journal.',6);saveGame();}
function pauseGame(){if(state!=='playing')return;state='paused';clearInput();saveGame();$('pauseLocation').textContent=ROOMS[room].name+' / '+D.bells.filter(Boolean).length+' of 3 old bells restored.';$('saveStatus').textContent=storageOK?'Your discoveries are saved in this browser.':'Browser storage is unavailable. Export a save to keep your discoveries.';showScreen('pause');}
function resumeGame(){if(state!=='paused')return;AudioSys.start();state='playing';clearInput();showScreen('');}
function openSettings(){previousScreen=state==='paused'?'pause':state==='menu'?'menu':activeScreen||'menu';state='settings';clearInput();$('quality').value=settings.quality;$('musicVol').value=Math.round(settings.music*100);$('sfxVol').value=Math.round(settings.sfx*100);$('assist').checked=settings.assist;$('shake').checked=settings.shake;$('showTouch').value=settings.touch;$('lookSensitivity').value=settings.lookSensitivity*100;showScreen('settings');}
function closeSettings(){saveJSON('bramblebound-settings',settings);if(previousScreen==='pause'){state='paused';showScreen('pause');}else showMenu();}
let mapReturn='playing';function openMap(){if(!gameStarted)return;mapReturn=state==='paused'?'paused':'playing';state='map';clearInput();drawAtlas();showScreen('map');}
function closeMap(){state=mapReturn;showScreen(state==='paused'?'pause':'');clearInput();}
function talk(lines,callback=null){dialogQueue=lines.map(l=>typeof l==='string'?{name:'Nori',text:l,portrait:'N'}:l);dialogIndex=0;dialogCallback=callback;dialogAge=0;state='dialogue';clearInput();showScreen('');setDialogueLine();}
function setDialogueLine(){let d=dialogQueue[dialogIndex];$('speaker').textContent=d.name;$('dialogLine').textContent=controlText(d.text);$('portrait').textContent=d.portrait||d.name[0];$('portrait').style.background=d.portrait==='N'?'#ba763f':'#5c7952';$('dialogPage').textContent=(dialogIndex+1)+' / '+dialogQueue.length;dialogAge=0;AudioSys.fx('ui');}
function advanceDialogue(){if(state!=='dialogue'||dialogAge<.16)return;if(++dialogIndex<dialogQueue.length)setDialogueLine();else{let cb=dialogCallback;dialogCallback=null;state='playing';showScreen('');clearInput();if(cb)cb();}}
function reward(title,text,emblem='&#10022;',callback=null){state='reward';clearInput();$('rewardTitle').textContent=title;$('rewardText').textContent=controlText(text);$('rewardEmblem').innerHTML=emblem;rewardCallback=callback;showScreen('reward');AudioSys.fx('reward');saveGame();}
function finishReward(){if(state!=='reward')return;let cb=rewardCallback;rewardCallback=null;state='playing';clearInput();showScreen('');if(cb)cb();updateObjective();}
function travel(to,spawn){if(transitioning||!ROOMS[to])return;transitioning=true;state='transition';clearInput();showScreen('');$('travelCaption').textContent=ROOMS[to].name;$('fade').classList.add('on');saveGame();setTimeout(()=>{try{buildWorld(to,spawn);state='playing';showScreen('');saveGame();$('fade').classList.remove('on');transitioning=false;hint(roomHint(),7);}catch(e){Support.fail(e);}},380);}
function roomHint(){if(room==='hearth')return D.ring?'Tab: map and journal. Golden arches lead to the next part of your story.':'Hold E and walk into the wooden crate to push it onto the brass plate.';if(room==='brook')return 'Jump between islands. Face a rune target and throw your sunring with Q.';if(room==='sun')return 'Press Space again in the air for Windstep. Ride the moving platforms.';if(room==='moon')return 'Hold J, then release for a sunlit spin. Press E beside a prism to turn its arrow.';if(room==='hollow')return 'Golden mushrooms launch you higher. Some discoveries are off the main path.';return 'Read the guardian: jump the rings, dodge the roots, then throw at its golden eyes.';}
function portalReady(p){if(!p.requires)return true;if(p.requires==='ring')return D.ring;if(p.requires.startsWith('bell'))return!!D.bells[+p.requires.slice(4)];return false;}
function bellReady(index){if(index===0)return ['reed','river','sun'].every(s=>D.flags['brook.'+s]);if(index===1)return['west','east','high'].every(s=>D.flags['sun.spindle-'+s]);return prisms.length===3&&prisms.every(p=>p.dir===p.want)||D.flags.moonSolved;}
function countRiver(){return ['reed','river','sun'].filter(s=>D.flags['brook.'+s]).length;}
function countWind(){return ['west','east','high'].filter(s=>D.flags['sun.spindle-'+s]).length;}
function goal(){if(D.won)return['A VALLEY FULL OF STORIES','Take the long way home',D.moths.length<6?'There are still star moths waiting to be found.':'Visit Pip. Every little light has found its way.'];if(room==='hollow')return['AN UNMARKED PATH','A light in the hollow','Use the golden mushroom to reach the high ledge.'];if(room==='crown')return['THE FINAL BELL','Wake the old guardian','Jump the rings. Ring the golden eyes. Strike while stunned.'];if(room==='moon'&&!D.bells[2])return['THE MOON BELL','Give the light a way through','Turn the three prisms. Follow the beam to the bell.'];if(room==='sun'&&!D.bells[1])return['THE SKY BELL','Catch the wandering wind',countWind()+' / 3 wind spindles found. Climb to the summit.'];if(room==='brook'&&!D.bells[0])return['THE RIVER BELL',countRiver()<3?'Ring the river runes':'The river remembers',countRiver()<3?countRiver()+' / 3 rune targets lit. Throw your sunring with Q.':'The old bridge is open. Find the bell at the far shrine.'];
if(!D.ring){if(!D.flags.metMoss)return['A MORNING GONE MISSING','Find the bellkeeper','Moss is in the village square. Press E to talk.'];return['A BORROWED LITTLE MIRACLE','Open the sunring workshop','Hold E and push the crate onto the round brass plate.'];}if(!D.bells[0])return['THE FIRST OLD ROAD','Follow the running water','The eastern arch leads to Brookfall.'];if(!D.bells[1])return['A SKY WITH ROOM FOR YOU','Climb the Sunstep Ruins','Take the western arch. Your new air jump opens the way.'];if(!D.bells[2])return['A LIGHT THAT NEEDS A GUIDE','Find Moonroot Sanctuary','The northern arch leads into the quiet forest.'];return['THREE BELLS. ONE MORNING.','Enter the Hollow Crown','The great tree waits beyond the northeastern arch.'];}
function updateObjective(){let g=goal();$('goalTag').textContent=g[0];$('goalTitle').textContent=g[1];$('goalDesc').textContent=controlText(g[2]);$('ringAction').classList.toggle('locked',!D.ring);$('jumpLabel').textContent=D.airjump?'Air jump':'Jump';$('placeLabel').textContent=ROOMS[room].name.toUpperCase();}
let healthCache='';function updateHUD(){updateTouchHUD();let key=player.hp+':'+player.maxHp;if(key!==healthCache){healthCache=key;let html='';for(let i=0;i<player.maxHp/2;i++){let f=clamp((player.hp-i*2)/2,0,1);html+=`<svg class="heart" viewBox="0 0 28 27" aria-label="${f===1?'Full':f===.5?'Half':'Empty'} heart"><defs><linearGradient id="h${i}"><stop offset="${f*100}%" stop-color="#ef967c"/><stop offset="${f*100}%" stop-color="#426251"/></linearGradient></defs><path d="M14 24C11 21 2 15 2 8C2 1 11 0 14 6C18 0 26 1 26 8C26 15 17 22 14 24Z" fill="url(#h${i})" stroke="#ffe5be" stroke-width="1.3"/></svg>`;}$('hearts').innerHTML=html;}
$('coinCount').textContent=D.coins;$('mothCount').textContent=D.moths.length+' / 6 STAR MOTHS';for(let i=0;i<3;i++)$('chime'+i).classList.toggle('got',D.bells[i]);$('ringAction').classList.toggle('ready',D.ring&&!sunring&&player.ringCD<=0);$('bossHud').style.display=boss?.awakened&&!D.won?'block':'none';if(boss){$('bossFill').style.width=clamp(boss.hp/boss.max*100,0,100)+'%';let text=boss.mode==='charge'?'JUMP THE SHOCKWAVE':boss.mode==='roots'?'KEEP MOVING: ROOTS ARE RISING':boss.mode==='open'?'GOLDEN EYES: THROW YOUR SUNRING':boss.mode==='stunned'?'STUNNED: CLOSE IN AND STRIKE':'Watch its hands. Keep your distance.';$('bossCue').textContent=text;}}
function addCoin(amount=1,id=null){if(id&&D.collected.includes(id))return;if(id)D.collected.push(id);D.coins+=amount;D.totalAcorns+=amount;AudioSys.fx('coin');updateHUD();}
function spawnLoot(x,z,y,id,n=2,health=false){for(let i=0;i<n;i++){let a=i/n*TAU;let key=id+'.drop'+i;if(!D.collected.includes(key))items.push({id:key,kind:'coin',x:x+Math.sin(a)*.45,z:z+Math.cos(a)*.45,y:y+.85,base:y+.85,phase:i,delay:.18});}if(health&&player.hp<player.maxHp)items.push({id:id+'.health',kind:'health',x,z,y:y+.85,base:y+.85,phase:0,delay:.18});}
function triggerSwitch(s){if(s.on)return;s.on=true;s.hit=.4;D.flags[s.id]=true;AudioSys.fx('switch');burst(s.x,s.y+2.2,s.z,24,[1,.77,.35]);if(countRiver()===3){D.flags.brookBridge=true;toast('Three notes, one old bridge. The northern shrine is open.',5);shake=.08;}else toast('River rune awakened. '+countRiver()+' / 3',2.5);updateObjective();saveGame();}
function collectBell(o){if(!bellReady(o.index)){hint(o.index===0?'The bell is sealed. Ring all three targets with the sunring.':o.index===1?'Find all three wind spindles on the terraces below.':'The light needs to reach the receiver beside the bell.',6);AudioSys.fx('ui');return;}D.bells[o.index]=true;o.gone=true;player.hp=player.maxHp;AudioSys.fx('bell');burst(o.x,o.y,o.z,70,[1,.80,.31],5);saveGame();
if(o.index===0){D.airjump=true;reward('Windstep','The River Bell has remembered its song. Press Space again while airborne to leap a second time. Higher paths now wait in the Sunstep Ruins.','&#8767;',()=>hint('Windstep learned. Press Space twice to air jump. The arch behind the shrine returns home.',9));}
else if(o.index===1){D.empowered=true;reward('The Sunlit Blade','The Sky Bell lends your little blade a bigger light. Hold J, then release to spin through dark brambles. Moonroot Sanctuary is ready to let you in.','&#10038;',()=>hint('Sunlit Blade learned. Hold J and release for an empowered spinning strike.',8));}
else{reward('Three notes. One morning.','The Moon Bell answers. All three paths now lead home. The arch beneath Hearthgrove\'s great tree will open for you.','&#9790;',()=>hint('Return to Hearthgrove. The northeastern arch now leads to the Hollow Crown.',9));}updateObjective();saveGame();}
function openChest(o){if(o.opened)return;o.opened=true;D.flags[o.id]=true;burst(o.x,o.y+1,o.z,32,[1,.74,.25]);AudioSys.fx('reward');if(o.reward==='ring'){D.ring=true;D.flags.metMoss=true;reward('The Sunring','An old courier\'s trick: throw it, and it always finds its way home. Press Q to strike rune targets, stun armored beetles, and collect out-of-reach acorns. Face a target for assisted aim.','&#9678;',()=>hint('Sunring acquired. Take the eastern arch into Brookfall. Press E beneath the arch.',9));}else{addCoin(o.value);toast('A little treasure: '+o.value+' acorns.',4);}saveGame();updateObjective();}
function talkNPC(n){AudioSys.fx('ui');if(n.id==='moss'){if(!D.flags.metMoss){D.flags.metMoss=true;talk([{name:n.name,text:'The morning bell never rang, Nori. Three old bells keep this valley awake. Something has stolen their song.',portrait:'M'},{name:n.name,text:'Borrow the sunring from my workshop to the east. Hold E and walk into the crate to push it onto the brass plate. The workshop gate will open.',portrait:'M'},{name:n.name,text:'Then follow the eastern arch to Brookfall. And remember: a lantern will always bring you safely home.',portrait:'M'}],()=>{updateObjective();saveGame();hint('Workshop: to the right of the square. Hold E to push the crate onto its brass plate.',10);});}else{let text=D.won?'You brought us a morning, Nori. I would have settled for a decent cup of tea. But this will do beautifully.':D.bells.every(Boolean)?'Three bells, three bright notes. Take the northeastern arch beneath the great tree. The old keeper is waiting.':!D.ring?'The workshop plate is round and brass. Hold E while walking into the wooden crate. Push it north onto the plate.':!D.bells[0]?'The eastern arch leads to Brookfall. Face its three rune targets and throw the sunring. Some will need a little jumping to reach.':!D.bells[1]?'The western arch is open. Your Windstep lets you jump again in the air. Follow the acorns up the Sunstep Ruins.':'Moonroot lies through the northern arch. Turn the prisms to carry the light around the sanctuary.';talk([{name:n.name,text,portrait:'M'}]);}}
else if(n.id==='toma')openShop();
else if(n.id==='pip'){if(D.moths.length===6&&!D.flags.mothReward){D.flags.mothReward=true;player.maxHp+=2;D.maxHp=player.maxHp;player.hp=player.maxHp;talk([{name:n.name,text:'Six little lights! Every one of them. You took the paths nobody asked you to take. This heart vessel belongs to a wanderer like you.',portrait:'P'}],()=>reward('A heart for the long road','Pip\'s six star moths are home. Your maximum health increases by one heart. Some of the best adventures happen between the important things.','&#9829;'));saveGame();}else talk([{name:n.name,text:D.moths.length===6?'All my little lights, safe and sound. You will always have a place here, Nori.':'My six star moths wandered off when the morning went missing. They like high places, quiet corners, and secrets behind waterfalls. Bring them home and I will have something for you. You have found '+D.moths.length+' of 6.',portrait:'P'}]);}
else if(n.id==='reed')talk([{name:n.name,text:'Three rune targets, three notes. One on the western bank, one on the eastern bank, and one by the far shrine. The sunring can reach what your feet cannot.',portrait:'R'},{name:n.name,text:'Face your target and press Q. The floating stones can carry you closer. And listen: that waterfall on the west bank sounds a little hollow.',portrait:'R'}]);
else if(n.id==='wren')talk([{name:n.name,text:'A second jump is a second chance. Tap Space again in the air, or save it until just before you land. Gold-capped mushrooms give you a generous lift.',portrait:'W'},{name:n.name,text:'The three wind spindles sit on different terraces. Follow their glow upward. The lantern on the high western terrace will remember how far you came.',portrait:'W'}]);
else if(n.id==='lumen')talk([{name:n.name,text:'The prisms remember where to send the light, but they have forgotten which way to face. Press E to turn an arrow. Follow each beam to the next prism.',portrait:'L'},{name:n.name,text:'The path is east, then north, then west. The light begins at the southwestern lantern. Hold J and release to clear the dark brambles in your way.',portrait:'L'}]);
else if(n.id==='warden')talk([{name:'The old bellkeeper',text:'I held the morning so tightly that I forgot to let it go. Thank you for reminding an old tree how to open its hands.',portrait:'W'}]);}
function updateNear(){let best=null,dist=2.45;const consider=(type,o,label,key='E',radius=2.45)=>{if(Math.abs(player.y-(o.y||0))>2.2)return;let d=Math.hypot(player.x-o.x,player.z-o.z);if(d<radius&&d<dist){dist=d;best={type,o,label,key};}};
for(let p of portals)consider('portal',p,portalReady(p)?'Travel to '+p.label:!D.ring?'Find the sunring first':p.requires==='bell0'?'The River Bell will open this path':p.requires==='bell1'?'The Sky Bell will open this path':'Restore all three bells');
for(let n of npcs)if(!n.afterWin||D.won)consider('npc',n,n.id==='toma'?'Trade with Toma':'Talk to '+n.name.split(',')[0]);for(let c of items)if(!c.gone&&c.kind==='chest'&&!c.opened)consider('chest',c,'Open the chest');for(let c of items)if(!c.gone&&c.kind==='bell')consider('bell',{...c,y:c.y-1.6,original:c},bellReady(c.index)?'Ring the old bell':'Read the bell seal','E',2.55);
for(let p of prisms)consider('prism',p,'Turn the light prism');for(let c of crates)consider('crate',c,'Hold E + move to push','E',1.9);for(let c of checkpoints)consider('lantern',c,'Rest at the lantern','E',1.8);
near=best;if(best&&state==='playing'){$('prompt').innerHTML='<kbd>'+(touchEnabled?(best.type==='crate'?'PUSH':'USE'):best.key)+'</kbd>'+controlText(best.label);$('prompt').style.display='block';}else $('prompt').style.display='none';updateTouchHUD();}
function interact(){if(!near)return;let {type,o}=near;if(type==='npc')talkNPC(o);else if(type==='chest')openChest(o);else if(type==='bell')collectBell(o.original||o);else if(type==='portal'){if(portalReady(o))travel(o.to,o.spawn);else hint(near.label+'. Your journal (Tab) shows the next step.',5);}else if(type==='prism'){o.dir=(o.dir+1)%4;D.prisms=prisms.map(p=>p.dir);AudioSys.fx('switch');burst(o.x,1.6,o.z,12,[.6,1,.8]);if(prisms.every(p=>p.dir===p.want)){D.flags.moonSolved=true;toast('The light has found its way. The Moon Bell is awake.',6);AudioSys.fx('bell');}updateObjective();saveGame();}else if(type==='lantern')activateLantern(o,true);else if(type==='crate')hint('Keep E held and walk toward the crate. Push it north onto the brass plate.',5);}
function activateLantern(c,manual=false){if(!manual&&c.cool>0)return;let same=D.checkpoint?.id===c.id;if(same&&player.hp===player.maxHp&&!manual)return;D.checkpoint={room,x:c.x+1.15,y:c.y,z:c.z+1.05,id:c.id};player.hp=player.maxHp;player.invuln=Math.max(player.invuln,.6);c.cool=5;AudioSys.fx('save');burst(c.x,c.y+2.2,c.z,14,[1,.79,.37]);toast('Lantern lit. Health restored. Your way is remembered.',3.2);saveGame();updateHUD();}
function returnToLantern(fall=false){let c=D.checkpoint||{room,x:ROOMS[room].spawn[0],y:ROOMS[room].spawn[1],z:ROOMS[room].spawn[2]};if(c.room!==room){travel(c.room,[c.x,c.y,c.z]);return;}if(fall){D.stats.falls++;if(!settings.assist)player.hp-=1;AudioSys.fx('hurt');}if(player.hp<=0||!fall)player.hp=player.maxHp;
player.x=c.x;player.y=c.y+.02;player.z=c.z;player.vx=player.vy=player.vz=0;player.roll=0;player.attack=0;player.charge=0;player.grounded=true;player.jumps=0;player.floorId='';player.invuln=2;sunring=null;projectiles=[];rings=[];cameraState.x=player.x;cameraState.y=player.y;cameraState.z=player.z;if(boss&&!D.won){boss.hp=boss.max;boss.mode='sleep';boss.awakened=false;boss.timer=1;boss.extra=0;boss.x=0;boss.z=-5;}
if(room==='hearth'&&!D.flags.workshop&&crates[0]){crates[0].x=5.8;crates[0].z=.6;}state='playing';showScreen('');clearInput();toast(fall?'A lantern remembers the way. Your collection is safe.':'A fresh breath. Back at your last lantern.',3);updateHUD();}
function hurt(damage,source=null){if(state!=='playing'||player.invuln>0||player.roll>0)return;let n=settings.assist?Math.max(1,Math.ceil(damage/2)):damage;player.hp=Math.max(0,player.hp-n);player.invuln=1.25;player.charge=0;shake=.13;AudioSys.fx('hurt');if(source){let dx=player.x-source.x,dz=player.z-source.z,l=Math.hypot(dx,dz)||1;player.vx=dx/l*5.5;player.vz=dz/l*5.5;player.vy=Math.max(player.vy,3);player.grounded=false;}
$('hitvignette').style.opacity='1';setTimeout(()=>$('hitvignette').style.opacity='0',230);updateHUD();if(player.hp<=0){D.flags.faints=(D.flags.faints||0)+1;returnToLantern(false);}}
function damageEnemy(e,amount,type='blade'){if(e.dead||e.hit>0)return false;if(e.type==='beetle'&&type==='blade'&&e.stun<=0){let dx=player.x-e.x,dz=player.z-e.z,l=Math.hypot(dx,dz)||1,dot=(dx*Math.sin(e.angle)+dz*Math.cos(e.angle))/l;if(dot>-.2){AudioSys.fx('ui');burst(e.x,e.y+.8,e.z,7,[1,.9,.55],2);if(!D.flags.armorHint){D.flags.armorHint=true;hint('Armored beetles: stun with Q, stomp from above, or get behind them.',6);}return false;}}
e.hp-=amount;e.hit=.19;e.stun=Math.max(e.stun,type==='ring'?2.8:.28);e.mode='idle';e.timer=.8;AudioSys.fx('hit');burst(e.x,e.y+.7,e.z,16,[.93,.73,.36]);hitStop=.035;shake=Math.max(shake,.045);
if(e.hp<=0){e.dead=true;if(!D.defeated.includes(e.id))D.defeated.push(e.id);D.stats.kills++;AudioSys.fx('pop');burst(e.x,e.y+.7,e.z,26,[.53,.75,.35],3);spawnLoot(e.x,e.z,e.y,e.id,3,Math.random()<.65);saveGame();}return true;}
function smashProps(radius,omni=false){const forward=[Math.sin(player.angle),Math.cos(player.angle)],within=o=>{let dx=o.x-player.x,dz=o.z-player.z,l=Math.hypot(dx,dz);return l<radius&&Math.abs(o.y-player.y)<1.5&&(omni||(dx*forward[0]+dz*forward[1])/(l||1)>-.15);};
for(let b of plants)if(!b.cut&&within(b)){b.cut=true;D.flags[b.id]=true;burst(b.x,b.y+.4,b.z,14,[.45,.7,.23],2);spawnLoot(b.x,b.z,b.y,b.id,1,Math.random()<.18);AudioSys.fx('pop');}
for(let b of pots)if(!b.broken&&within(b)){b.broken=true;D.flags[b.id]=true;burst(b.x,b.y+.4,b.z,16,[.7,.41,.25],2.8);spawnLoot(b.x,b.z,b.y,b.id,2,Math.random()<.3);AudioSys.fx('pop');}
for(let b of thorns)if(!b.broken&&within(b)){if(b.strong&&(!D.empowered||!omni)){hint('Dark brambles need a sunlit spin: hold J, then release.',4);continue;}b.broken=true;D.flags[b.id]=true;burst(b.x,b.y+.8,b.z,35,[.72,.71,.28],4);AudioSys.fx('pop');saveGame();}}
function damageBoss(amount){if(!boss||boss.mode!=='stunned'||boss.hit>0)return;boss.hp=Math.max(0,boss.hp-amount);boss.hit=.23;AudioSys.fx('hit');burst(boss.x,boss.y+2.3,boss.z+1,30,[1,.82,.38],4);shake=.13;hitStop=.055;
if(boss.hp<=0){winGame();return;}if(boss.stunHP-boss.hp>=6){boss.mode='charge';boss.timer=1.8;boss.cycle++;toast('The roots loosen. Read the next opening.',2.6);}updateHUD();}
function startAttack(spin=false){if(state!=='playing'||player.roll>0)return;if(!spin&&player.attackCD>0){player.attackBuffer=.18;return;}let p=player;if(spin){p.spin=.50;p.attack=0;p.attackCD=.55;AudioSys.fx('spin');}else{let target=enemies.filter(e=>!e.dead&&Math.hypot(e.x-p.x,e.z-p.z)<2.65&&Math.abs(e.y-p.y)<1.5).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(target)p.angle=Math.atan2(target.x-p.x,target.z-p.z);p.combo=p.comboTimer>0?(p.combo+1)%3:0;p.comboTimer=.9;p.attack=.34;p.attackCD=.25;AudioSys.fx('swing');}
let radius=spin?3.7:2.65,damage=spin?(D.empowered?3:2):(D.empowered?2:p.combo===2?2:1);for(let e of enemies){let dx=e.x-p.x,dz=e.z-p.z,d=Math.hypot(dx,dz);if(!e.dead&&d<radius&&Math.abs(e.y-p.y)<1.7&&(spin||(dx*Math.sin(p.angle)+dz*Math.cos(p.angle))/(d||1)>-.1))damageEnemy(e,damage,spin&&D.empowered?'sunspin':'blade');}
if(boss&&Math.hypot(boss.x-p.x,boss.z-p.z)<4.0&&p.y<3.5){if(boss.mode==='stunned')damageBoss(spin?3:2);else if(!D.flags.bossArmorHint){D.flags.bossArmorHint=true;hint('The bark is sealed. Wait for golden eyes, then stun it with your sunring.',7);}}
smashProps(radius,spin);}
function throwRing(){if(!D.ring){hint('The sunring waits in the village workshop.',4);return;}if(sunring||player.ringCD>0||state!=='playing')return;let p=player,origin=[p.x,p.y+1.12,p.z],candidates=[];const add=(id,kind,x,y,z,bias=0)=>{let dx=x-p.x,dz=z-p.z,d=Math.hypot(dx,dz),dot=(dx*Math.sin(p.angle)+dz*Math.cos(p.angle))/(d||1);if(d< (D.flags.longRing?18:14)&&d>.15&&Math.abs(y-origin[1])<6&&canSee(origin,[x,y,z]))candidates.push({id,kind,x,y,z,score:d+(dot<.2?5:0)+bias});};
for(let s of switches)if(!s.on)add(s.id,'switch',s.x,s.y+2.2,s.z,-1);for(let e of enemies)if(!e.dead)add(e.id,'enemy',e.x,e.y+.7,e.z,0);if(boss?.awakened)add('boss','boss',boss.x+Math.sin(boss.ang)*1.1,boss.y+2.25,boss.z+Math.cos(boss.ang)*1.1,boss.mode==='open'?-5:1);
candidates.sort((a,b)=>a.score-b.score);let target=candidates[0],dir=target?V.norm(V.sub([target.x,target.y,target.z],origin)):[Math.sin(p.angle),0,Math.cos(p.angle)];if(target)p.angle=Math.atan2(target.x-p.x,target.z-p.z);sunring={x:origin[0],y:origin[1],z:origin[2],dx:dir[0],dy:dir[1],dz:dir[2],out:true,travel:0,time:0,hits:new Set(),trail:[],target:target?.id};p.ringCD=.30;AudioSys.fx('ring');}
function updateSunring(dt){if(!sunring)return;let r=sunring;r.time+=dt;let speed=r.out?20:27;let old=[r.x,r.y,r.z];if(r.out){r.x+=r.dx*speed*dt;r.y+=r.dy*speed*dt;r.z+=r.dz*speed*dt;r.travel+=speed*dt;if(r.travel>(D.flags.longRing?18:14)||r.time>.95)r.out=false;if(blockedPoint(r.x,r.y,r.z,.10)){r.out=false;r.x=old[0];r.y=old[1];r.z=old[2];}}
else{let dir=V.sub([player.x,player.y+1.1,player.z],[r.x,r.y,r.z]),len=V.len(dir);if(len<.6||r.time>3){sunring=null;return;}let k=Math.min(1,speed*dt/len);r.x+=dir[0]*k;r.y+=dir[1]*k;r.z+=dir[2]*k;}
r.trail.push([r.x,r.y,r.z]);if(r.trail.length>8)r.trail.shift();for(let s of switches)if(!s.on&&Math.hypot(s.x-r.x,s.z-r.z)<.8&&Math.abs(s.y+2.2-r.y)<.8)triggerSwitch(s);
for(let e of enemies)if(!e.dead&&!r.hits.has(e.id)&&Math.hypot(e.x-r.x,e.z-r.z)<.85&&Math.abs(e.y+.7-r.y)<1){r.hits.add(e.id);damageEnemy(e,D.flags.longRing?2:1,'ring');}
if(boss?.awakened&&!r.hits.has('boss')&&Math.hypot(boss.x-r.x,boss.z-r.z)<1.8&&Math.abs(boss.y+2.3-r.y)<1.7){r.hits.add('boss');if(boss.mode==='open'){boss.mode='stunned';boss.timer=5.5;boss.stunHP=boss.hp;r.out=false;AudioSys.fx('bell');burst(boss.x,3,boss.z,55,[1,.85,.35],4);toast('The keeper is stunned. Close in and strike!',3);shake=.13;}else if(boss.mode!=='stunned')hint('Wait until its eyes turn gold. That is your opening.',4);}
for(let o of items)if(!o.gone&&o.kind==='coin'&&Math.hypot(o.x-r.x,o.z-r.z)<.65&&Math.abs(o.y-r.y)<.9){o.gone=true;addCoin(1,o.id);burst(o.x,o.y,o.z,6,[1,.8,.3],1);}}
function roll(){if(player.roll>0||player.rollCD>0)return;player.roll=.34;player.rollCD=.68;let speed=Math.hypot(player.vx,player.vz),dx=speed>.6?player.vx/speed:Math.sin(player.angle),dz=speed>.6?player.vz/speed:Math.cos(player.angle);player.rollDX=dx;player.rollDZ=dz;player.angle=Math.atan2(dx,dz);player.charge=0;AudioSys.fx('roll');}
function updateMovers(dt){for(let p of moving){p.px=p.x;p.pz=p.z;p.py=p.y;const val=Math.sin(t*p.speed+p.phase)*p.amp;if(p.axis==='x')p.x=p.baseX+val;else if(p.axis==='z')p.z=p.baseZ+val;else p.y=p.baseY+val;p.bottom=p.y-.5;if(player.grounded&&player.floorId===p.id){player.x+=p.x-p.px;player.z+=p.z-p.pz;player.y+=p.y-p.py;}}}
function updatePlayer(dt){const p=player;for(let key of['invuln','attack','attackCD','comboTimer','spin','roll','rollCD','jumpBuffer','coyote','land','ringCD','attackBuffer'])p[key]=Math.max(0,p[key]-dt);
let ax=(held.has('KeyD')||held.has('ArrowRight')?1:0)-(held.has('KeyA')||held.has('ArrowLeft')?1:0)+touchVector.x+padVector.x,az=(held.has('KeyS')||held.has('ArrowDown')?1:0)-(held.has('KeyW')||held.has('ArrowUp')?1:0)+touchVector.y+padVector.y,l=Math.hypot(ax,az);if(l>1){ax/=l;az/=l;l=1;}let cs=Math.cos(cameraState.yaw),sn=Math.sin(cameraState.yaw),mx=ax*cs+az*sn,mz=-ax*sn+az*cs;
if(consume('Space'))p.jumpBuffer=.15;if(consume('KeyJ')){p.charge=0;p.spinConsumed=false;startAttack();}if(consume('KeyK'))roll();if(consume('KeyQ')||consume('KeyL'))throwRing();
if(held.has('KeyJ'))p.charge+=dt;if(released.has('KeyJ')){if(p.charge>=.55&&!p.spinConsumed)startAttack(true);p.charge=0;p.spinConsumed=false;}if(p.charge>.65&&!p.spinConsumed&&Math.abs(p.charge-.65)<dt*2)AudioSys.fx('switch');if(p.attackBuffer>0&&p.attackCD<=0){p.attackBuffer=0;startAttack();}
if(p.jumpBuffer>0&&((p.grounded||p.coyote>0)||D.airjump&&p.jumps<2)){let air=!(p.grounded||p.coyote>0);if(air){p.jumps=2;AudioSys.fx('double');burst(p.x,p.y+.15,p.z,24,[.84,.85,.36],3);}else{p.jumps=1;AudioSys.fx('jump');}p.vy=air?10.4:10.6;p.grounded=false;p.coyote=0;p.jumpBuffer=0;p.floorId='';D.stats.jumps++;}
if(released.has('Space')&&p.vy>4)p.vy*=.56;
let speed=(held.has('ShiftLeft')||held.has('ShiftRight')||touchRunning?8.9:6.7)+(D.flags.sash?.75:0);if(p.attack>0)speed*=.80;if(held.has('KeyE'))speed*=.65;
const accel=p.grounded?38:36,damp=p.grounded?44:22;const approach=(v,target,amount)=>v<target?Math.min(target,v+amount):Math.max(target,v-amount);if(p.roll>0){p.vx=p.rollDX*12.2;p.vz=p.rollDZ*12.2;}else{let tx=mx*speed-p.vx,tz=mz*speed-p.vz,dd=Math.hypot(tx,tz),cap=(l>.05?accel:damp)*dt;if(dd>cap){tx*=cap/dd;tz*=cap/dd;}p.vx+=tx;p.vz+=tz;if(l>.08&&p.attack<=.08)p.angle=Math.atan2(mx,mz);}
// Holding interact turns body contact into a deliberate push, never an accidental shove.
p.holdingCrate=false;if(held.has('KeyE')&&l>.1&&p.grounded){for(let c of crates){let dx=c.x-p.x,dz=c.z-p.z,d=Math.hypot(dx,dz);if(d<1.80&&Math.abs(c.y-p.y)<.3&&(dx*mx+dz*mz)/(d||1)>.25){p.holdingCrate=true;resolveAxis(c,'x',p.vx*dt,.65,1.2,c.id);resolveAxis(c,'z',p.vz*dt,.65,1.2,c.id);c.x=clamp(c.x,-22,22);c.z=clamp(c.z,-23,23);}}}
let lastX=p.x,lastZ=p.z;resolveAxis(p,'x',p.vx*dt);resolveAxis(p,'z',p.vz*dt);let oldY=p.y,wasGround=p.grounded;
if(p.grounded){let floor=floorAt(p.x,p.z,p.y+.33);if(floor&&floor.y>=p.y-.40){p.y=floor.y;p.floorId=floor.id;p.vy=0;p.coyote=.13;}else{p.grounded=false;p.coyote=.13;p.jumps=Math.max(1,p.jumps);p.floorId='';}}
if(!p.grounded){oldY=p.y;p.vy-=27*dt;p.y+=p.vy*dt;let stomp=false;if(p.vy<0)for(let e of enemies)if(!e.dead&&Math.hypot(e.x-p.x,e.z-p.z)<.87&&oldY>=e.y+.95&&p.y<e.y+1.18&&oldY>e.y+.85){damageEnemy(e,2,'stomp');p.y=e.y+1.22;p.vy=9.8;p.jumps=1;stomp=true;AudioSys.fx('double');break;}
if(!stomp&&p.vy<=0){let best=null;for(let s of surfaces())if(insideSurface(s,p.x,p.z,.035)&&oldY>=s.y-.12&&p.y<=s.y&&(!best||s.y>best.y))best=s;if(best){p.y=best.y;p.grounded=true;p.floorId=best.id;p.coyote=.13;p.jumps=0;p.land=.14;if(p.vy<-8){AudioSys.fx('land');burst(p.x,p.y+.07,p.z,7,[.61,.66,.32],1.1);}p.vy=0;}}
}
if(p.grounded){for(let s of springs)if(s.cool<=0&&Math.hypot(p.x-s.x,p.z-s.z)<s.r&&Math.abs(p.y-s.y)<.15){s.cool=.35;p.vy=17;p.grounded=false;p.jumps=1;p.floorId='';AudioSys.fx('double');burst(p.x,p.y+.8,p.z,25,[1,.8,.3],4);hint('A little lift! Save your air jump for extra height.',3);}}
let distance=Math.hypot(p.x-lastX,p.z-lastZ);D.stats.steps+=distance;p.walk+=distance*3.7;if(p.grounded&&distance>.005){p.stepTimer-=dt;if(p.stepTimer<=0){p.stepTimer=.27;AudioSys.fx('step');}}
if(p.y<-4.2||Math.abs(p.x)>110||Math.abs(p.z)>110)returnToLantern(true);
}
function moveEnemy(e,dx,dz,dt){let oldX=e.x,oldZ=e.z;resolveAxis(e,'x',dx*dt,.42,1.0);resolveAxis(e,'z',dz*dt,.42,1.0);let f=floorAt(e.x,e.z,e.y+.3);if(!f||Math.abs(f.y-e.homeY)>.5){e.x=oldX;e.z=oldZ;e.angle+=Math.PI*.6;return false;}e.y=f.y;return Math.hypot(e.x-oldX,e.z-oldZ)>.004;}
function updateEnemies(dt){for(let e of enemies){if(e.dead)continue;e.t+=dt;e.hit=Math.max(0,e.hit-dt);e.stun=Math.max(0,e.stun-dt);e.timer-=dt;let dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz),height=Math.abs(player.y-e.y),within=d<9&&height<2.7;let angle=Math.atan2(dx,dz);
if(e.stun<=0){if(e.mode==='windup'){e.angle=angle;if(e.timer<=0){if(e.type==='spitter'){let dir=V.norm([dx,player.y+.75-(e.y+.65),dz]);projectiles.push({x:e.x,y:e.y+.68,z:e.z,vx:dir[0]*5.8,vy:dir[1]*5.8,vz:dir[2]*5.8,life:4});e.mode='recover';e.timer=1.8;AudioSys.fx('ring');}else{e.mode='lunge';e.timer=e.type==='beetle'?.58:.38;e.attackDir=[Math.sin(e.angle),Math.cos(e.angle)];}}}
else if(e.mode==='lunge'){let speed=e.type==='beetle'?9:6;moveEnemy(e,e.attackDir[0]*speed,e.attackDir[1]*speed,dt);if(e.timer<=0){e.mode='recover';e.timer=1.15;}}
else if(e.mode==='recover'){if(e.timer<=0){e.mode='idle';e.timer=.6;}}
else if(within){e.angle=angle;if((e.type==='spitter'&&d<8||e.type!=='spitter'&&d<2.9)&&canSee([e.x,e.y+.75,e.z],[player.x,player.y+.75,player.z])){e.mode='windup';e.timer=e.type==='beetle'?.82:e.type==='spitter'?.85:.62;}else{e.mode='chase';let speed=e.type==='beetle'?1.45:e.type==='spitter'?.8:2.0;let homeDist=Math.hypot(e.x-e.homeX,e.z-e.homeZ);if(homeDist<e.range+3)moveEnemy(e,dx/(d||1)*speed,dz/(d||1)*speed,dt);else{e.mode='idle';e.timer=1;moveEnemy(e,(e.homeX-e.x)*.5,(e.homeZ-e.z)*.5,dt);}}}
else{e.mode='idle';if(e.timer<=0){e.timer=1+Math.random()*2;e.angle=Math.random()*TAU;}if(Math.hypot(e.x-e.homeX,e.z-e.homeZ)>e.range)e.angle=Math.atan2(e.homeX-e.x,e.homeZ-e.z);moveEnemy(e,Math.sin(e.angle)*.38,Math.cos(e.angle)*.38,dt);}}
if(e.stun<=0&&d<(e.type==='beetle'?1.05:.78)&&player.y<e.y+1.03&&player.y+1.3>e.y&&e.hit<=0)hurt(e.type==='beetle'?2:1,e);
}}
function updateBoss(dt){if(!boss||D.won)return;let b=boss;b.t+=dt;b.hit=Math.max(0,b.hit-dt);if(!b.awakened){if(player.z<7){b.awakened=true;b.mode='charge';b.timer=1.8;b.cycle=0;toast('The Briar Warden stirs. Watch its hands.',4);AudioSys.fx('warning');updateHUD();}return;}b.phase=b.hp>12?0:b.hp>6?1:2;b.ang=Math.atan2(player.x-b.x,player.z-b.z);b.timer-=dt;
if(b.extra>0){b.extra-=dt;if(b.extra<=0)rings.push({kind:'shock',x:b.x,z:b.z,y:0,r:.3,speed:8.5,life:5,hit:false});}
if(b.mode==='charge'&&b.timer<=0){b.mode='slam';b.timer=1.8;AudioSys.fx('slam');shake=.22;rings.push({kind:'shock',x:b.x,z:b.z,y:0,r:.3,speed:8+b.phase*.4,life:5,hit:false});if(b.phase>0)b.extra=1.0;burst(b.x,.3,b.z,40,[.62,.62,.31],6);}
else if(b.mode==='slam'&&b.timer<=0){b.mode='roots';b.timer=1.35;let pattern=[[player.x,player.z]];if(b.phase>0)pattern.push([clamp(player.x+3,-14,14),player.z-1]);if(b.phase>1)pattern.push([clamp(player.x-3,-14,14),player.z+2]);for(let [x,z]of pattern)rings.push({kind:'danger',x,z,y:0,r:2,delay:.9,life:2.0,active:false,hit:false});}
else if(b.mode==='roots'&&b.timer<=0){b.mode='open';b.timer=5.5;AudioSys.fx('switch');hint('Now! Face the guardian and throw the sunring with Q.',5.5);}
else if(b.mode==='open'&&b.timer<=0){b.mode='charge';b.timer=1.5;}
else if(b.mode==='stunned'&&b.timer<=0){b.mode='charge';b.timer=1.8;b.cycle++;}
let d=Math.hypot(player.x-b.x,player.z-b.z);if(b.mode!=='stunned'&&d<1.7&&player.y<2.5)hurt(2,b);}
function updateHazards(dt){for(let r of rings){r.life-=dt;if(r.kind==='shock'){r.r+=r.speed*dt;let d=Math.hypot(player.x-r.x,player.z-r.z);if(!r.hit&&Math.abs(d-r.r)<.40&&player.y<.78){r.hit=true;hurt(2,r);}}else if(r.kind==='danger'){r.delay-=dt;r.active=r.delay<=0;if(r.active&&!r.hit&&Math.hypot(player.x-r.x,player.z-r.z)<r.r&&player.y<1.0){r.hit=true;hurt(2,r);}}}rings=rings.filter(r=>r.life>0);
for(let p of projectiles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;if(blockedPoint(p.x,p.y,p.z,.08))p.life=0;if(Math.hypot(player.x-p.x,player.z-p.z)<.5&&p.y>player.y+.05&&p.y<player.y+1.6){hurt(1,p);p.life=0;burst(p.x,p.y,p.z,8,[.57,.68,.54],1);}}projectiles=projectiles.filter(p=>p.life>0);
for(let h of hazards)if(h.kind==='sweeper'){let a=visualTime*.72,dx=player.x-h.x,dz=player.z-h.z,along=dx*Math.sin(a)+dz*Math.cos(a),across=dx*Math.cos(a)-dz*Math.sin(a);if(Math.abs(along)<h.r&&Math.abs(across)<.30&&Math.abs(player.y-h.y)<.70)hurt(1,h);}}
function updateItems(dt){for(let o of items){if(o.gone)continue;o.delay=Math.max(0,(o.delay||0)-dt);if(o.delay>0)continue;let y=o.y,d=Math.hypot(o.x-player.x,o.z-player.z);if(o.kind==='coin'&&d<1.75&&Math.abs(y-(player.y+.7))<1.5){let pull=1-Math.exp(-dt*10);o.x=lerp(o.x,player.x,pull);o.z=lerp(o.z,player.z,pull);if(d<.7){o.gone=true;addCoin(1,o.id);burst(o.x,y,o.z,5,[1,.85,.3],1);}}
else if(o.kind==='health'&&d<.9&&Math.abs(y-(player.y+.7))<1.1&&player.hp<player.maxHp){o.gone=true;player.hp=Math.min(player.maxHp,player.hp+2);AudioSys.fx('save');updateHUD();}
else if(o.kind==='moth'&&d<1.0&&Math.abs(y-(player.y+.8))<1.45){o.gone=true;D.moths.push(o.id);AudioSys.fx('moth');burst(o.x,y,o.z,30,[1,.82,.36]);toast('A star moth found its way to you. '+D.moths.length+' / 6',4);updateHUD();saveGame();}
else if(o.kind==='spindle'&&d<.9&&Math.abs(y-(player.y+.8))<1.3){o.gone=true;D.flags[o.id]=true;AudioSys.fx('switch');burst(o.x,y,o.z,30,[1,.78,.24]);toast(countWind()===3?'Three wind spindles. The Sky Bell is awake.':'A wind spindle. '+countWind()+' / 3',4);updateObjective();saveGame();}}
}
function updatePuzzles(dt){if(room==='hearth'&&!D.flags.workshop){let c=crates[0];if(c&&Math.hypot(c.x-5.8,c.z+4)<.72){D.flags.workshop=true;c.x=5.8;c.z=-4;AudioSys.fx('switch');burst(5.8,.2,-4,25,[1,.8,.3]);toast('The workshop gate is open. A little treasure is waiting.',5);saveGame();}}
for(let c of checkpoints){c.cool=Math.max(0,(c.cool||0)-dt);if(Math.hypot(c.x-player.x,c.z-player.z)<1.38&&Math.abs(c.y-player.y)<.2)activateLantern(c);}
for(let s of springs)s.cool=Math.max(0,s.cool-dt);}
function winGame(){if(D.won)return;D.won=true;player.hp=player.maxHp;projectiles=[];rings=[];AudioSys.fx('bell');burst(boss.x,3,boss.z,120,[1,.82,.36],7);boss=null;ornaments.push({kind:'restored-heart',x:0,z:-5,y:2.5});saveGame();talk([{name:'The old bellkeeper',text:'I only meant to keep the morning safe. Then the roots grew around it... and I forgot how to let go.',portrait:'W'},{name:'Nori',text:'You do not have to keep it all by yourself.',portrait:'N'},{name:'The old bellkeeper',text:'No. I suppose I never did.',portrait:'W'}],()=>{state='ending';$('endTime').textContent=formatTime(D.stats.time);$('endAcorns').textContent=D.totalAcorns;$('endMoths').textContent=D.moths.length+' / 6';$('endingStory').textContent=D.moths.length===6?'The bells rang over the valley. Six little moths carried their light between the trees, and the old keeper opened his hands. For the first time in a very long while, Hearthgrove woke to the sun.':'The bells rang over the valley. Light threaded its way through the branches, and the old keeper opened his hands. For the first time in a very long while, Hearthgrove woke to the sun.';showScreen('ending');saveGame();});}
let nearTimer=0,hudTimer=0,saveTimer=0;
function update(dt){t+=dt;D.stats.time+=dt;if(hitStop>0){hitStop-=dt;return;}updateMovers(dt);updatePlayer(dt);if(state!=='playing')return;updateSunring(dt);updateEnemies(dt);updateBoss(dt);updateHazards(dt);updateItems(dt);updatePuzzles(dt);nearTimer-=dt;if(nearTimer<=0){nearTimer=.09;updateNear();}if(consume('KeyE')){updateNear();interact();}
for(let p of particles){p.life-=dt;p.x+=(p.vx||0)*dt;p.y+=(p.vy||0)*dt;p.z+=(p.vz||0)*dt;p.vy=(p.vy||0)-(p.gravity||0)*dt;}particles=particles.filter(p=>p.life>0);hudTimer-=dt;if(hudTimer<=0){hudTimer=.12;updateHUD();drawMiniMap();}saveTimer+=dt;if(saveTimer>15){saveTimer=0;saveGame();}pressed.clear();released.clear();}
