// State, portable saves, synthesized original audio, and input. No network APIs are used.
const SAVE_KEY='bramblebound-story-v1';
function newData(){return{version:1,room:'hearth',checkpoint:{room:'hearth',x:0,y:0,z:16},bells:[false,false,false],ring:false,airjump:false,empowered:false,coins:0,totalAcorns:0,maxHp:8,flags:{},collected:[],moths:[],defeated:[],prisms:[0,2,1],won:false,stats:{time:0,jumps:0,falls:0,kills:0,steps:0}};}
function validateSave(v){if(!v||v.version!==1||!['hearth','brook','hollow','sun','moon','crown'].includes(v.room))throw Error('This is not a compatible Bramblebound save.');let d=newData();d.room=v.room;d.bells=Array.from({length:3},(_,i)=>!!v.bells?.[i]);d.ring=!!v.ring||d.bells.some(Boolean);d.airjump=!!v.airjump||d.bells[0];d.empowered=!!v.empowered||d.bells[1];d.won=!!v.won;d.coins=clamp(Math.floor(+v.coins||0),0,9999);d.totalAcorns=clamp(Math.floor(+v.totalAcorns||0),d.coins,99999);d.maxHp=clamp(Math.floor((+v.maxHp||8)/2)*2,8,18);
for(let k of['collected','moths','defeated'])d[k]=Array.isArray(v[k])?[...new Set(v[k].filter(x=>typeof x==='string'&&/^[a-zA-Z0-9_.-]{1,70}$/.test(x)))].slice(0,2000):[];
d.moths=d.moths.filter(id=>['hearth-star','brook-star','hollow-star','sun-star-low','sun-star-high','moon-star'].includes(id));if(v.flags&&typeof v.flags==='object')for(let[k,val]of Object.entries(v.flags).slice(0,1000))if(/^[a-zA-Z0-9_.-]{1,70}$/.test(k)&&!['__proto__','constructor','prototype'].includes(k)&&(typeof val==='boolean'||typeof val==='number'))d.flags[k]=val;
d.prisms=Array.from({length:3},(_,i)=>clamp(Math.floor(+v.prisms?.[i]||0),0,3));for(let k of Object.keys(d.stats))d.stats[k]=clamp(+v.stats?.[k]||0,0,9999999);
let c=v.checkpoint;if(c&&c.room===d.room&&['x','y','z'].every(k=>Number.isFinite(c[k]))&&Math.abs(c.x)<100&&Math.abs(c.z)<100&&c.y>=0&&c.y<25)d.checkpoint={room:c.room,x:c.x,y:c.y,z:c.z};else d.checkpoint=null;
if(d.room==='brook'&&!d.ring||d.room==='sun'&&!d.bells[0]||d.room==='moon'&&!d.bells[1]||d.room==='crown'&&!d.bells[2]){d.room='hearth';d.checkpoint={room:'hearth',x:0,y:0,z:16};}return d;}
let D=newData(),savedData=null;try{let loaded=loadJSON(SAVE_KEY,null);if(loaded)savedData=validateSave(loaded);}catch(e){Support.note('Save ignored: '+e.message);}
let state='loading',previousScreen='menu',activeScreen='',t=0,visualTime=0,hitStop=0,shake=0,areaTimer=0,toastTimer=0,hintTimer=0,transitioning=false,gameStarted=false;
const player={x:0,y:0,z:16,vx:0,vy:0,vz:0,angle:0,face:Math.PI,hp:8,maxHp:8,grounded:true,coyote:.14,jumpBuffer:0,jumps:0,jumpHeld:false,invuln:0,attack:0,combo:0,comboTimer:0,attackCD:0,attackBuffer:0,charge:0,spin:0,spinConsumed:false,roll:0,rollCD:0,rollDX:0,rollDZ:1,floorId:'',land:0,walk:0,ringCD:0,stepTimer:0,holdingCrate:false};
let particles=[],projectiles=[],rings=[],sunring=null,near=null;
const cameraState={x:0,y:0,z:16,yaw:0,distance:19,drag:false,lastX:0};
let toastText='',dialogQueue=[],dialogIndex=0,dialogCallback=null,dialogAge=0,rewardCallback=null;
function saveGame(){if(!gameStarted)return false;D.stats.time=Math.max(0,D.stats.time);D.maxHp=player.maxHp;let ok=saveJSON(SAVE_KEY,D);savedData=JSON.parse(JSON.stringify(D));return ok;}
function exportSave(){if(touchEnabled){openSaveTools('export');return;}saveGame();downloadText('bramblebound-save.json',JSON.stringify(D,null,2));toast('Your story is packed. Save file exported.');}
function formatTime(s){return Math.floor(s/60)+'m '+String(Math.floor(s%60)).padStart(2,'0')+'s';}
const AudioSys=(()=>{let ctx=null,master=null,music=null,sfx=null,next=0,step=0,coinPitch=0,lastCoin=0;function start(){if(!ctx){try{ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.8;master.connect(ctx.destination);music=ctx.createGain();sfx=ctx.createGain();music.connect(master);sfx.connect(master);apply();next=ctx.currentTime+.1;}catch(e){Support.note('Audio unavailable: '+e.message);return;}}if(ctx.state==='suspended'||ctx.state==='interrupted')ctx.resume().catch(()=>{});}
function apply(){if(!ctx)return;music.gain.setTargetAtTime(settings.music*.27,ctx.currentTime,.12);sfx.gain.setTargetAtTime(settings.sfx*.42,ctx.currentTime,.08);}
function tone(freq,when,duration=.22,gain=.1,type='triangle',bus='sfx',end=null){if(!ctx||ctx.state!=='running')return;let o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(20,freq),when);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),when+duration);g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(gain,when+.008);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g);g.connect(bus==='music'?music:sfx);o.start(when);o.stop(when+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
function noise(duration,gain=.05,filter=1800){if(!ctx||ctx.state!=='running')return;let n=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),data=n.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);let source=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();source.buffer=n;f.type='lowpass';f.frequency.value=filter;g.gain.value=gain;source.connect(f);f.connect(g);g.connect(sfx);source.start();source.onended=()=>{source.disconnect();f.disconnect();g.disconnect();};}
const midi=n=>440*2**((n-69)/12);
function fx(kind){if(!ctx||ctx.state!=='running')return;let n=ctx.currentTime;if(kind==='coin'){coinPitch=n-lastCoin<.5?(coinPitch+1)%8:0;lastCoin=n;let f=midi([76,79,81,84,86,88,91,93][coinPitch]);tone(f,n,.14,.16,'sine');tone(f*2,n+.025,.09,.035,'sine');}else if(kind==='jump'){tone(250,n,.17,.13,'triangle','sfx',650);noise(.08,.025,900);}else if(kind==='double'){tone(450,n,.24,.13,'sine','sfx',1100);tone(700,n+.04,.20,.06,'sine');}else if(kind==='land'){noise(.08,.04,400);tone(90,n,.09,.05,'sine');}else if(kind==='step'){noise(.055,.018,350);}else if(kind==='swing'){noise(.12,.11,1800);tone(370,n,.11,.045,'triangle','sfx',140);}else if(kind==='spin'){noise(.36,.11,2400);tone(250,n,.30,.11,'triangle','sfx',880);}else if(kind==='ring'){tone(700,n,.25,.11,'sine','sfx',450);tone(1050,n+.03,.20,.05,'triangle');}else if(kind==='hit'){noise(.12,.10,1000);tone(140,n,.14,.17,'triangle','sfx',65);}else if(kind==='hurt'){tone(190,n,.23,.16,'triangle','sfx',75);noise(.19,.07,500);}else if(kind==='pop'){tone(300,n,.16,.13,'sine','sfx',620);tone(500,n+.045,.18,.08,'sine','sfx',900);}else if(kind==='roll'){noise(.2,.07,700);tone(170,n,.17,.07,'sine','sfx',240);}else if(kind==='switch'){[72,76,79].forEach((m,i)=>tone(midi(m),n+i*.07,.42,.11,'sine'));}else if(kind==='reward'){[60,64,67,72,76,79,84].forEach((m,i)=>tone(midi(m),n+i*.085,.8,.11,'triangle'));}else if(kind==='bell'){[60,67,72,79].forEach((m,i)=>{tone(midi(m),n+i*.14,1.6,.13,'sine');tone(midi(m)*2.01,n+i*.14,1.1,.025,'sine');});}else if(kind==='save'){[72,79,84].forEach((m,i)=>tone(midi(m),n+i*.1,.4,.08,'sine'));}else if(kind==='ui'){tone(540,n,.07,.06,'sine');}else if(kind==='warning'){tone(180,n,.6,.12,'triangle','sfx',220);}else if(kind==='slam'){noise(.5,.25,500);tone(65,n,.6,.28,'sine','sfx',30);}else if(kind==='moth'){[81,84,88,93].forEach((m,i)=>tone(midi(m),n+i*.09,.5,.09,'sine'));}}
function tick(){if(!ctx||ctx.state!=='running')return;if(!['playing','dialogue','reward','transition','ending'].includes(state)){next=ctx.currentTime+.15;return;}if(next<ctx.currentTime-.5)next=ctx.currentTime+.05;let battle=!!boss?.awakened&&!D.won,beat=battle?.24:regionStyle==='night'?.37:.31;
while(next<ctx.currentTime+.12){let bar=Math.floor(step/16)%4,root=[48,45,41,43][bar],mel=[12,16,19,16,14,12,7,9,12,19,21,19,16,14,12,7];if(step%2===0){let note=root+mel[step%16]+(battle?0:12);tone(midi(note),next,.5,.14,'triangle','music');tone(midi(note)*2,next,.3,.018,'sine','music');}if(step%4===0){tone(midi(root),next,.8,.21,'sine','music');tone(midi(root+7),next,.9,.035,'triangle','music');}if(step%8===0)[0,4,7,11].forEach(k=>tone(midi(root+12+k),next,1.7,.025,'sine','music'));if(battle&&step%2===0)tone(step%4?110:58,next,.18,.12,'triangle','music',32);step++;next+=beat;}}
return{start,apply,fx,tick,get context(){return ctx;}};})();
const held=new Set(),pressed=new Set(),released=new Set();let touchVector={x:0,y:0},padVector={x:0,y:0},padDown=new Set(),inputSource='keyboard';
function keyDown(code){if(!held.has(code))pressed.add(code);held.add(code);}
function keyUp(code){held.delete(code);released.add(code);}
function clearInput(){resetTouchInputs();cameraState.drag=false;held.clear();pressed.clear();released.clear();touchVector.x=touchVector.y=0;padVector.x=padVector.y=0;player.charge=0;player.spinConsumed=false;document.getElementById('knob').style.transform='';}
function consume(code){if(pressed.has(code)){pressed.delete(code);return true;}return false;}
const controlled=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyJ','KeyQ','KeyK','KeyL','KeyE','Tab','Escape','KeyP','ShiftLeft','ShiftRight']);
window.addEventListener('keydown',e=>{if(!controlled.has(e.code)&&e.code!=='Enter')return;if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)&&e.code!=='Escape')return;if(state==='playing'||(state==='paused'&&e.code==='Space')||e.code==='Escape'||(['dialogue','reward'].includes(state)&&['KeyE','Space','Enter'].includes(e.code))||(e.code==='Tab'&&['map','playing'].includes(state)))e.preventDefault();if(e.repeat)return;inputSource='keyboard';routeButton(e.code,true);});
window.addEventListener('keyup',e=>{keyUp(e.code);});
function routeButton(code,down){if(!down){keyUp(code);return;}AudioSys.start();if(code==='Escape'||code==='KeyP'){if(state==='playing')pauseGame();else if(state==='paused')resumeGame();else if(state==='map')closeMap();else if(state==='settings')closeSettings();else if(state==='about')showMenu();else if(state==='saveTools')closeSaveTools();else if(state==='shop'){state='playing';showScreen('');clearInput();}else if(state==='dialogue')advanceDialogue();else if(state==='reward')finishReward();return;}
if(state==='dialogue'&&['KeyE','Space','Enter'].includes(code)){advanceDialogue();return;}if(state==='reward'&&['KeyE','Space','Enter'].includes(code)){finishReward();return;}if(code==='Tab'&&state==='playing'){openMap();return;}if(code==='Tab'&&state==='map'){closeMap();return;}if(state==='menu'&&code==='Enter'){savedData?continueGame():startNew();return;}if(state==='paused'&&code==='Space'){resumeGame();return;}if(state==='playing')keyDown(code);}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;if(state!=='playing')return;AudioSys.start();if(e.button===2){cameraState.drag=true;cameraState.lastX=e.clientX;}if(e.button===0)keyDown('KeyJ');});
window.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'&&cameraState.drag&&state==='playing'){cameraState.yaw-= (e.clientX-cameraState.lastX)*.005;cameraState.lastX=e.clientX;}});window.addEventListener('pointerup',e=>{if(e.pointerType==='touch')return;if(e.button===2)cameraState.drag=false;if(e.button===0)keyUp('KeyJ');});canvas.addEventListener('wheel',e=>{if(state==='playing'){e.preventDefault();cameraState.distance=clamp(cameraState.distance+e.deltaY*.012,13,26);}},{passive:false});
function pollGamepad(dt){let pads=[];try{pads=navigator.getGamepads?navigator.getGamepads():[];}catch{return;}let p=Array.from(pads).find(x=>x&&x.connected);if(!p){padVector.x=padVector.y=0;for(let key of padDown)keyUp(key);padDown.clear();return;}const dead=n=>Math.abs(n||0)<.2?0:(Math.abs(n)-.2)/.8*Math.sign(n);padVector.x=dead(p.axes[0]);padVector.y=dead(p.axes[1]);if(Math.hypot(padVector.x,padVector.y)>.1)inputSource='gamepad';if(state==='playing')cameraState.yaw-=dead(p.axes[2])*dt*1.7;
const map={0:'Space',1:'KeyK',2:'KeyJ',3:'KeyE',5:'KeyQ',8:'Tab',9:'Escape'};for(let [idx,key]of Object.entries(map)){let on=!!p.buttons[idx]?.pressed;if(on&&!padDown.has(key)){padDown.add(key);inputSource='gamepad';if(state==='menu'&&key==='Space'){savedData?continueGame():startNew();}else if(state==='paused'&&key==='KeyK'){resumeGame();}else routeButton(key,true);}if(!on&&padDown.has(key)){padDown.delete(key);keyUp(key);}}
}
window.addEventListener('blur',()=>{cameraState.drag=false;clearInput();if(state==='playing')pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state==='playing')pauseGame();}});
