// The atlas, in-world shop, settings, and startup. All menus use normal browser focus.
function drawMiniMap(){let c=$('minimap'),g=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2,scale=4.7;g.clearRect(0,0,w,h);g.save();g.beginPath();g.arc(cx,cy,cx-2,0,TAU);g.clip();g.fillStyle=regionStyle==='night'?'#254b4e':'#275447';g.fillRect(0,0,w,h);const project=(x,z)=>{let dx=x-player.x,dz=z-player.z,cs=Math.cos(cameraState.yaw),sn=Math.sin(cameraState.yaw);return[cx+(dx*cs-dz*sn)*scale,cy+(dx*sn+dz*cs)*scale];};
for(let s of surfaces()){let points=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>project(s.x+x*s.w/2,s.z+z*s.d/2));g.beginPath();points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.fillStyle=room==='sun'?'#819761':regionStyle==='night'?'#657d78':'#709566';g.fill();g.strokeStyle='#b6c49a50';g.lineWidth=1.4;g.stroke();}
for(let s of solids){let p=project(s.x,s.z);g.fillStyle='#254b3855';g.fillRect(p[0]-s.w*scale/2,p[1]-s.d*scale/2,s.w*scale,s.d*scale);}
function point(x,z,r,color,diamond=false){let p=project(x,z);g.fillStyle=color;g.beginPath();if(diamond){g.moveTo(p[0],p[1]-r);g.lineTo(p[0]+r,p[1]);g.lineTo(p[0],p[1]+r);g.lineTo(p[0]-r,p[1]);g.closePath();}else g.arc(...p,r,0,TAU);g.fill();}
for(let p of portals)point(p.x,p.z,6,portalReady(p)?'#ffe1a0':'#254936',true);for(let o of items)if(!o.gone){if(o.kind==='coin')point(o.x,o.z,1.7,'#efcb7d');if(o.kind==='spindle'||o.kind==='bell')point(o.x,o.z,5,'#ffdfa1',true);if(o.kind==='moth')point(o.x,o.z,3,'#fff4c7',true);}for(let n of npcs)if(!n.afterWin||D.won)point(n.x,n.z,4,'#e8e1be');for(let s of switches)point(s.x,s.z,4,s.on?'#f6d48e':'#afd6cf',true);for(let e of enemies)if(!e.dead)point(e.x,e.z,3,'#d59079');for(let p of prisms)point(p.x,p.z,4,'#a9dfca',true);for(let c of checkpoints)point(c.x,c.z,3,'#ffebb4');if(boss)point(boss.x,boss.z,7,'#e4a976');
g.save();g.translate(cx,cy);g.rotate(-(player.angle-cameraState.yaw));g.fillStyle='#ffefc5';g.strokeStyle='#183d35';g.lineWidth=2;g.beginPath();g.moveTo(0,8);g.lineTo(-5,-5);g.lineTo(0,-2);g.lineTo(5,-5);g.closePath();g.fill();g.stroke();g.restore();g.restore();g.fillStyle='#f3e6bf';g.font='bold 16px Georgia';g.textAlign='center';g.fillText('N',cx+Math.sin(cameraState.yaw)*(cx-17),cy-Math.cos(cameraState.yaw)*(cy-17)+5);}
function drawAtlas(){let c=$('bigmap'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);g.fillStyle='#dedebc';g.fillRect(0,0,w,h);let rnd=rng(390);for(let i=0;i<1200;i++){g.fillStyle=i%2?'#e9e2bf40':'#87996b16';g.fillRect(rnd()*w,rnd()*h,2,2);}const nodes={hearth:{x:450,y:245,r:69,label:'Hearthgrove',sub:'Home & the workshop'},brook:{x:756,y:252,r:71,label:'Brookfall',sub:'The River Bell'},sun:{x:155,y:225,r:67,label:'Sunstep Ruins',sub:'The Sky Bell'},moon:{x:436,y:71,r:57,label:'Moonroot',sub:'The Moon Bell'},crown:{x:777,y:70,r:56,label:'The Hollow Crown',sub:'The old keeper'},hollow:{x:916,y:351,r:32,label:'Hidden Hollow',sub:'A quiet secret'}};
function road(a,b){g.strokeStyle='#ad9b6a';g.lineWidth=3;g.setLineDash([5,8]);g.beginPath();g.moveTo(a.x,a.y);g.bezierCurveTo(a.x+(b.x-a.x)*.45,a.y+25,b.x-(b.x-a.x)*.35,b.y+20,b.x,b.y);g.stroke();g.setLineDash([]);}road(nodes.hearth,nodes.brook);road(nodes.hearth,nodes.sun);road(nodes.hearth,nodes.moon);road(nodes.hearth,nodes.crown);road(nodes.brook,nodes.hollow);
for(let [key,n]of Object.entries(nodes)){g.fillStyle=key==='brook'?'#a1bdaa':key==='moon'||key==='hollow'?'#a4b7a7':key==='sun'?'#c2b377':'#b7c38b';g.beginPath();for(let i=0;i<20;i++){let a=i/20*TAU,rr=n.r*(.88+Math.sin(i*3.9)*.1);let x=n.x+Math.cos(a)*rr*1.3,y=n.y+Math.sin(a)*rr*.73;if(i)g.lineTo(x,y);else g.moveTo(x,y);}g.closePath();g.fill();g.strokeStyle='#72886660';g.lineWidth=1;g.stroke();
for(let i=0;i<5;i++){let a=i/5*TAU,x=n.x+Math.cos(a)*n.r*.75,y=n.y+Math.sin(a)*n.r*.32;g.fillStyle=key==='sun'?'#a08d53':'#768d65';g.beginPath();g.moveTo(x,y-12);g.lineTo(x-7,y+1);g.lineTo(x+7,y+1);g.closePath();g.fill();g.strokeStyle='#7b7652';g.beginPath();g.moveTo(x,y);g.lineTo(x,y+6);g.stroke();}
if(key===room){g.strokeStyle='#a1813c';g.lineWidth=2.4;g.beginPath();g.arc(n.x,n.y,23,0,TAU);g.stroke();g.fillStyle='#faf0ce';g.beginPath();g.arc(n.x,n.y,18,0,TAU);g.fill();g.fillStyle='#b17343';g.beginPath();g.moveTo(n.x-9,n.y-10);g.lineTo(n.x-8,n.y+7);g.lineTo(n.x,n.y+12);g.lineTo(n.x+8,n.y+7);g.lineTo(n.x+9,n.y-10);g.lineTo(n.x,n.y-3);g.closePath();g.fill();}else{let done=key==='brook'?D.bells[0]:key==='sun'?D.bells[1]:key==='moon'?D.bells[2]:key==='crown'?D.won:false;g.fillStyle=done?'#e6c16f':'#dfe2bf';g.beginPath();g.arc(n.x,n.y,17,0,TAU);g.fill();g.fillStyle='#607052';g.font='19px Georgia';g.textAlign='center';g.fillText(done?'\u2713':key==='hearth'?'\u2302':key==='hollow'?'?':'\u2726',n.x,n.y+6);}
g.fillStyle='#34543e';g.font='bold '+(key==='hollow'?13:16)+'px Georgia';g.textAlign='center';g.fillText(n.label,n.x,n.y+n.r*.66+15);g.fillStyle='#75805c';g.font='10px Trebuchet MS';g.fillText(n.sub,n.x,n.y+n.r*.66+31);}
g.fillStyle='#84946b';g.font='italic 13px Georgia';g.textAlign='left';g.fillText('Every road has a story.',25,35);g.font='10px Trebuchet MS';g.fillText('Dotted paths connect the arches in Hearthgrove.',25,386);g.textAlign='right';g.fillText('A POCKET MAP OF THE WAKING VALLEY',972,24);
let goals=goal();$('journalGoal').textContent=controlText(goals[1]+'. '+goals[2]);$('journalSide').textContent=D.moths.length+' / 6 star moths found. '+D.totalAcorns+' acorns discovered. '+D.bells.filter(Boolean).length+' / 3 bells restored. '+(D.moths.length===6?'Pip is waiting in Hearthgrove.':'Pip keeps a reward for curious travelers.');}
function puzzleNudge(){let text='';if(room==='hearth'){text=!D.ring?'Stand just south of the crate (between it and the sign). Hold E and W to push it north onto the brass circle. The open gate is to its right.':goal()[2];}else if(room==='brook'){text=countRiver()<3?'The targets are on the west bank, east bank, and far shrine. Get within fourteen paces, face a target, and press Q. Use the moving northern stone to reach the last target.':'The bridge from the central mill to the north shrine is open. Jump onto it and ring the bell with E.';}else if(room==='sun'){text=countWind()<3?'Collect the glowing spindle on each of the three terraces: lower west, middle east, and upper west. Wait for a moving platform, then use your second jump late in the leap.':'The bell is at the highest shrine. From the upper west terrace, use the stepping stone and an air jump to reach the summit.';}else if(room==='moon'){text='Turn the western prism EAST, the middle-right prism NORTH, and the top-right prism WEST. Each press of E turns a prism clockwise. The beam shows your progress.';}else if(room==='crown'){text='Stay several steps away. Jump when a shock ring reaches you; higher phases send two rings. Move off the marked root circles. When the eyes glow gold, throw Q. Run in and strike the stunned core.';}else text='The gold-capped mushroom on the left launches you onto the low ledge. Jump from there to the high ledge. An air jump helps, but a mushroom launch also reaches it.';
$('journalGoal').textContent=controlText(text);AudioSys.fx('ui');}
const shop=document.createElement('section');shop.id='shop';shop.className='screen overlay';shop.innerHTML='<div class="paper"><div class="kicker">Toma\'s traveling workshop</div><h2>Good things for long roads.</h2><p id="shopPurse"></p><div id="shopCards" class="stat-grid"></div><p id="shopMessage" class="hint-note"></p><div class="row"><button class="primary" id="shopClose">Back to wandering <span>&rarr;</span></button></div></div>';document.body.appendChild(shop);
function openShop(){state='shop';clearInput();refreshShop();showScreen('shop');}
function refreshShop(){const vessels=Number(D.flags.vessels||0),list=[{id:'heart',title:'Heart vessel',desc:'One more full heart. Refills your health, too.',price:20+vessels*15,bought:vessels>=3,icon:'&#9829;'},{id:'sash',title:'Traveler\'s sash',desc:'A little more speed on every road. Permanent +0.75 movement speed.',price:25,bought:!!D.flags.sash,icon:'&#8767;'},{id:'longRing',title:'Sunring lining',desc:'Longer throws and stronger hits. Armored beetles will notice.',price:30,bought:!!D.flags.longRing,locked:!D.ring,icon:'&#9678;'}];$('shopPurse').textContent='You have '+D.coins+' acorns. Upgrades stay with you for the whole adventure.';$('shopCards').innerHTML='';for(let it of list){let el=document.createElement('div');el.className='statbox';el.innerHTML='<strong style="font-size:32px">'+it.icon+'</strong><h3 style="font:20px Georgia;margin:12px 0 6px">'+it.title+'</h3><p style="font-size:11px;line-height:1.6;min-height:58px">'+it.desc+'</p>';let b=document.createElement('button');b.className='secondary';b.style.cssText='width:100%;padding:11px 13px;font-size:11px';b.disabled=it.bought||it.locked||D.coins<it.price;b.textContent=it.bought?'Already yours':it.locked?'Find the sunring first':it.price+' acorns';b.onclick=()=>buy(it.id);el.appendChild(b);$('shopCards').appendChild(el);}$('shopMessage').textContent='Find acorns along paths, inside pots, and in hidden chests. Grass can hide a little treasure.';}
function buy(id){const price=id==='heart'?20+Number(D.flags.vessels||0)*15:id==='sash'?25:id==='longRing'?30:Infinity;if(D.coins<price)return;if(id==='heart'&&D.flags.vessels>=3||id!=='heart'&&D.flags[id])return;if(id==='longRing'&&!D.ring)return;D.coins-=price;if(id==='heart'){D.flags.vessels=(D.flags.vessels||0)+1;player.maxHp+=2;D.maxHp=player.maxHp;player.hp=player.maxHp;}else D.flags[id]=true;AudioSys.fx('reward');saveGame();updateHUD();refreshShop();}
$('shopClose').onclick=()=>{state='playing';showScreen('');clearInput();};
$('newBtn').onclick=()=>startNew();$('confirmNew').onclick=()=>startNew(true);$('cancelNew').onclick=showMenu;$('continueBtn').onclick=continueGame;$('menuSettings').onclick=openSettings;$('pauseSettings').onclick=openSettings;$('settingsBack').onclick=closeSettings;$('resumeBtn').onclick=resumeGame;$('pauseBtn').onclick=pauseGame;$('mapBtn').onclick=openMap;$('pauseMap').onclick=openMap;$('mapClose').onclick=closeMap;$('hintBtn').onclick=puzzleNudge;$('dialogNext').onclick=advanceDialogue;$('rewardContinue').onclick=finishReward;$('saveBtn').onclick=exportSave;$('endingSave').onclick=exportSave;
$('checkpointBtn').onclick=()=>returnToLantern(false);$('quitBtn').onclick=()=>{saveGame();clearInput();showMenu();};$('menuAbout').onclick=()=>{state='about';showScreen('about');};$('aboutBack').onclick=showMenu;$('exploreBtn').onclick=()=>travel('hearth',[0,0,6]);
$('quality').onchange=()=>{settings.quality=$('quality').value;try{Engine.resize();}catch(e){Support.fail(e);}saveJSON('bramblebound-settings',settings);};$('musicVol').oninput=()=>{settings.music=+$('musicVol').value/100;AudioSys.start();AudioSys.apply();};$('sfxVol').oninput=()=>{settings.sfx=+$('sfxVol').value/100;AudioSys.start();AudioSys.apply();};$('assist').onchange=()=>settings.assist=$('assist').checked;$('shake').onchange=()=>settings.shake=$('shake').checked;$('showTouch').onchange=()=>{settings.touch=$('showTouch').value;setTouch();};
$('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen&&document.fullscreenEnabled)await document.documentElement.requestFullscreen();else{$('fullscreenNote').textContent='Fullscreen is not offered here. Keep playing in this tab; landscape works without fullscreen.';return;}$('fullscreenNote').textContent='Fullscreen changed. You can also play in a normal browser tab.';}catch{$('fullscreenNote').textContent='Fullscreen was not allowed. The adventure still works in this tab.';}};
$('menuImport').onclick=()=>$('saveImport').click();$('saveImport').onchange=async e=>{let file=e.target.files?.[0];if(!file)return;try{if(file.size>400000)throw Error('Save file is too large.');let data=validateSave(JSON.parse(await file.text()));savedData=data;saveJSON(SAVE_KEY,data);continueGame();}catch(err){Support.note('Import rejected: '+err.message);alert('Could not import this save: '+err.message);}finally{e.target.value='';}};
// Boot, bounded fixed-step simulation, and a developer-only test interface.
setTouch();if(matchMedia('(prefers-reduced-motion:reduce)').matches)settings.shake=false;
state='menu';buildWorld('hearth',[0,0,16]);showMenu();updateHUD();drawMiniMap();
let lastFrame=performance.now(),accumulator=0,frames=0,raf=0;function frame(now){if(Support.isFailed())return;try{let dt=Math.min(.10,Math.max(0,(now-lastFrame)/1000));lastFrame=now;pollGamepad(dt);if(state==='playing'||state==='menu'||state==='confirm')visualTime+=dt;dialogAge+=dt;AudioSys.tick();
if(state==='playing'){accumulator+=dt;let n=0;while(accumulator>=1/60&&n++<6){update(1/60);accumulator-=1/60;if(state!=='playing'){accumulator=0;break;}}}else{accumulator=0;pressed.clear();released.clear();}
shake=Math.max(0,shake-dt*.8);if(areaTimer>0){areaTimer-=dt;if(areaTimer<.8)$('areaCard').style.opacity=String(Math.max(0,areaTimer/.8));}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('show');}if(hintTimer>0){hintTimer-=dt;if(hintTimer<=0)$('contextHint').style.opacity='0';}
renderFrame();if(++frames===2){$('boot').style.opacity='0';setTimeout(()=>$('boot').style.display='none',400);}raf=requestAnimationFrame(frame);}catch(e){Support.fail(e);}}
raf=requestAnimationFrame(frame);
window.Bramblebound={version:'1.1-mobile',saveCheckpoint:saveGame,diagnostics:()=>({...Support.report(),graphics:Engine.stats,room,state,storage:storageOK,touch:touchEnabled,touchPoints:navigator.maxTouchPoints,dpr:devicePixelRatio})};
if(location.hash.includes('qa'))window.__BB={get state(){return state;},get data(){return D;},get player(){return player;},get room(){return room;},get world(){return{grounds,solids,items,npcs,portals,checkpoints,switches,moving,crates,thorns,prisms,enemies,boss,sunring,rings};},get engine(){return Engine;},get settings(){return settings;},get camera(){return cameraState;},get audioState(){return AudioSys.context?.state||"not-created";},get input(){return{held:[...held],pressed:[...pressed],released:[...released],touch:{...touchVector},running:touchRunning,stickID,actionOwners:actionPointers.size,cameraOwners:cameraPointers.size};},syncViewport,setTouch,openSaveTools,closeSaveTools,start:()=>startNew(true),pause:pauseGame,resume:resumeGame,step:(n=1)=>{for(let i=0;i<n;i++){if(state==='playing'){visualTime+=1/60;update(1/60);}else dialogAge+=1/60;}},teleport:(x,y,z)=>{Object.assign(player,{x,y,z,vx:0,vy:0,vz:0,grounded:false,floorId:'',invuln:1});cameraState.x=x;cameraState.y=y;cameraState.z=z;},load:(name,p)=>{state='playing';buildWorld(name,p);showScreen('');},press:key=>routeButton(key,true),release:key=>routeButton(key,false),clear:clearInput,render:renderFrame,stop:()=>cancelAnimationFrame(raf),play:()=>{lastFrame=performance.now();raf=requestAnimationFrame(frame);},interact:()=>{updateNear();interact();},dialog:()=>{dialogAge=1;advanceDialogue();},reward:finishReward,save:saveGame,validate:validateSave,attack:startAttack,throw:throwRing,hurt,respawn:returnToLantern,floorAt,walls,canSee,goal,damageEnemy,damageBoss,triggerSwitch,collectBell,openChest,buy,openShop,openMap,closeMap,win:winGame,export:exportSave,pollGamepad,updateHUD,updateObjective};
